# Generated by Django 5.2 on 2026-05-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='旅行名')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='行き先')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('theme', models.CharField(blank=True, max_length=100, verbose_name='テーマ')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('preparing', '準備中'), ('ongoing', '旅行中'), ('organizing', '思い出整理中'), ('done', '完了')], default='planning', max_length=20, verbose_name='ステータス')),
                ('summary', models.TextField(blank=True, verbose_name='概要メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trip',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '食べたもの'), ('place', '行った場所'), ('buy', '買ったもの'), ('good', '良かったこと'), ('organize', 'あとで整理したいこと'), ('impression', 'ちょっとした感想')], default='impression', max_length=20, verbose_name='分類')),
                ('body', models.TextField(verbose_name='メモ')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_memos', to='trips.trip')),
            ],
            options={
                'db_table': 'travel_memo',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('belongings', '持ち物'), ('reservation', '予約確認'), ('purchase', '事前購入'), ('research', '調べること'), ('before_leaving', '家を出る前にやること')], default='belongings', max_length=20, verbose_name='分類')),
                ('name', models.CharField(max_length=200, verbose_name='項目名')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
            ],
            options={
                'db_table': 'packing_item',
                'ordering': ['category', 'is_done', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_place', models.TextField(blank=True, verbose_name='一番良かった場所')),
                ('revisit', models.TextField(blank=True, verbose_name='また行きたい場所')),
                ('delicious', models.TextField(blank=True, verbose_name='おいしかったもの')),
                ('impression', models.TextField(blank=True, verbose_name='印象に残ったこと')),
                ('next_time', models.TextField(blank=True, verbose_name='次回に活かすメモ')),
                ('journal', models.TextField(blank=True, verbose_name='AI生成の旅行記本文')),
                ('journal_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='旅行記生成日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='trips.trip')),
            ],
            options={
                'db_table': 'memory_entry',
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='時刻')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('reservation_number', models.CharField(blank=True, max_length=100, verbose_name='予約番号')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='trips.trip')),
            ],
            options={
                'db_table': 'itinerary_item',
                'ordering': ['date', 'time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('packing', '準備リスト提案'), ('question', '思い出整理の質問'), ('journal', '旅行記本文生成'), ('title', 'タイトル案')], max_length=20, verbose_name='種別')),
                ('model', models.CharField(max_length=50, verbose_name='使用モデル')),
                ('prompt', models.TextField(verbose_name='プロンプト')),
                ('response', models.TextField(verbose_name='応答')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'ai_suggestion_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='その日のタイトル')),
                ('note', models.TextField(blank=True, verbose_name='その日のメモ')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_day',
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
