# Generated by Django 5.2 on 2026-05-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelmemo',
            name='trip',
        ),
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='memoryentry',
            name='best_place',
        ),
        migrations.RemoveField(
            model_name='memoryentry',
            name='delicious',
        ),
        migrations.RemoveField(
            model_name='memoryentry',
            name='impression',
        ),
        migrations.RemoveField(
            model_name='memoryentry',
            name='next_time',
        ),
        migrations.RemoveField(
            model_name='memoryentry',
            name='revisit',
        ),
        migrations.AddField(
            model_name='trip',
            name='md_plan',
            field=models.TextField(blank=True, verbose_name='旅行計画（Markdown）'),
        ),
        migrations.CreateModel(
            name='MemoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to='trips.trip')),
            ],
            options={
                'db_table': 'memory_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ItineraryItem',
        ),
        migrations.DeleteModel(
            name='TravelMemo',
        ),
        migrations.DeleteModel(
            name='TripDay',
        ),
    ]
