# Generated by Django 5.2 on 2026-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_travelmemo_trip_alter_tripday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='best_shot',
            field=models.ImageField(blank=True, null=True, upload_to='best_shots/', verbose_name='ベストショット'),
        ),
        migrations.AddField(
            model_name='trip',
            name='best_shot_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='ベストショットの一言'),
        ),
    ]
