# Generated by Django 5.2 on 2026-05-05 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_best_shot_trip_best_shot_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
