# Generated by Django 5.2 on 2026-05-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestionlog',
            name='kind',
            field=models.CharField(choices=[('packing', '準備リスト提案'), ('question', '思い出整理の質問'), ('journal', '旅行記本文生成'), ('title', 'タイトル案'), ('shiori', 'しおり一括生成')], max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('preparing', '準備中'), ('done', '完了'), ('cancelled', '中止')], default='preparing', max_length=20, verbose_name='ステータス'),
        ),
    ]
