# Generated by Django 5.2 on 2026-05-10 08:21

from django.db import migrations, models


def migrate_cancelled_status(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    Trip.objects.filter(status="cancelled").update(is_cancelled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_simplify_status_choices'),
    ]

    operations = [
        # 先に is_cancelled を追加してからデータ変換し、最後に status を削除する
        migrations.AddField(
            model_name='trip',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='中止'),
        ),
        migrations.RunPython(migrate_cancelled_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
    ]
